/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Delance } from "./Delance";
export * as factories from "./factories";
export { Delance__factory } from "./factories/Delance__factory";
